site_name: MSU Cloud Computing Fellowship
nav:
    - Home: index.md
    - Contact: contact.md
    - About: about.md 
    - Sessions:
       - · Introduction: session_introduction/index.md
       - · How does the cloud work?: session_how_to_cloud/index.md
       - · Cloud Storage: session_cloud_storage/index.md
       - · Data Systems: session_datasystems/index.md
       - · Big Data and the cloud: session_bigdata/index.md       
       - · Serverless, Containers, and FaaS: session_serverless/index.md
       - · Cloud Services Organization: session_organization/index.md
       - · Mini-Project: miniproject.md
    - About Fellowship Projects: projects.md
    - References: references/index.md
    - Cloud Glossary: cloud_glossary.md
    - Previous 21-22 syllabus: index2021.md
theme: 
  name: material
  features:
    - navigation.sections
  palette:
    primary: black
markdown_extensions:
  - attr_list
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - md_in_html
extra:
  generator: false